# Generated by Django 2.1.5 on 2019-02-03 00:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20190203_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='kwargs',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='keyword arguments'),
        ),
    ]
