# Generated by Django 2.1.5 on 2019-02-06 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, help_text='used in the menu when fully deployed', max_length=127, verbose_name='menu label')),
                ('icon', models.CharField(help_text='according to your CSS framework\n                       used as visual identification everywhere it should\n                       used in the menu when reduced', max_length=16, verbose_name='CSS icon name')),
                ('parent', models.ForeignKey(blank=True, help_text='parent menu item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='menu.MenuItem', verbose_name='parent')),
                ('screen', models.OneToOneField(blank=True, help_text='If this is null, this menu item is a not a leaf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='screen.Screen', verbose_name='screen pointed by this menu item')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('parent', 'label'), ('parent', 'icon')},
        ),
        migrations.AlterIndexTogether(
            name='menuitem',
            index_together={('screen', 'icon'), ('parent', 'screen'), ('parent', 'screen', 'label'), ('screen', 'label')},
        ),
    ]
