# Generated by Django 2.1.5 on 2019-02-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screen', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='screen',
            field=models.OneToOneField(blank=True, help_text='If this is null, this menu item is a not a leaf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='screen.Screen', verbose_name='screen pointed by this menu item'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('parent', 'label'), ('parent', 'icon')},
        ),
        migrations.AlterIndexTogether(
            name='menuitem',
            index_together={('parent', 'screen'), ('screen', 'icon'), ('parent', 'screen', 'label'), ('screen', 'label')},
        ),
    ]
